<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // iso 3166 country code list from:
        // https://github.com/Svish/iso-3166-country-codes/blob/master/countries.sql

        Schema::create('continents', function (Blueprint $table) {
            $table->char('code', 2)->primary()->comment('Continent code');
            $table->string('name', 255);
        });

        DB::table('continents')->insert([
            ['code' => 'AF', 'name' => 'Africa'],
            ['code' => 'AS', 'name' => 'Asia'],
            ['code' => 'EU', 'name' => 'Europe'],
            ['code' => 'NA', 'name' => 'North America'],
            ['code' => 'SA', 'name' => 'South America'],
            ['code' => 'OC', 'name' => 'Oceania'],
            ['code' => 'AN', 'name' => 'Antarctica'],
        ]);

        Schema::create('countries', function (Blueprint $table) {
            $table->char('code', 2)->primary()->comment('Two-letter country code (ISO 3166-1 alpha-2)');
            $table->char('continent_code', 2)->comment('Continent code');
            $table->string('name', 255)->comment('English country name');
            $table->char('iso3', 3)->comment('Three-letter country code (ISO 3166-1 alpha-3)');
            $table->char('number', 3)->comment('Continent code');
            $table->string('full_name', 255)->comment('Three-digit country number (ISO 3166-1 numeric)');
        });

        DB::table('countries')->insert([
            ['code' => 'AF', 'continent_code' => 'AS', 'name' => 'Afghanistan', 'iso3' => 'AFG', 'number' => '004', 'full_name' => 'Islamic Republic of Afghanistan'],
            ['code' => 'AX', 'continent_code' => 'EU', 'name' => 'Åland Islands', 'iso3' => 'ALA', 'number' => '248', 'full_name' => 'Åland Islands'],
            ['code' => 'AL', 'continent_code' => 'EU', 'name' => 'Albania', 'iso3' => 'ALB', 'number' => '008', 'full_name' => 'Republic of Albania'],
            ['code' => 'DZ', 'continent_code' => 'AF', 'name' => 'Algeria', 'iso3' => 'DZA', 'number' => '012', 'full_name' => "People's Democratic Republic of Algeria"],
            ['code' => 'AS', 'continent_code' => 'OC', 'name' => 'American Samoa', 'iso3' => 'ASM', 'number' => '016', 'full_name' => 'American Samoa'],
            ['code' => 'AD', 'continent_code' => 'EU', 'name' => 'Andorra', 'iso3' => 'AND', 'number' => '020', 'full_name' => 'Principality of Andorra'],
            ['code' => 'AO', 'continent_code' => 'AF', 'name' => 'Angola', 'iso3' => 'AGO', 'number' => '024', 'full_name' => 'Republic of Angola'],
            ['code' => 'AI', 'continent_code' => 'NA', 'name' => 'Anguilla', 'iso3' => 'AIA', 'number' => '660', 'full_name' => 'Anguilla'],
            ['code' => 'AQ', 'continent_code' => 'AN', 'name' => 'Antarctica', 'iso3' => 'ATA', 'number' => '010', 'full_name' => 'Antarctica (the territory South of 60 deg S)'],
            ['code' => 'AG', 'continent_code' => 'NA', 'name' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'number' => '028', 'full_name' => 'Antigua and Barbuda'],
            ['code' => 'AR', 'continent_code' => 'SA', 'name' => 'Argentina', 'iso3' => 'ARG', 'number' => '032', 'full_name' => 'Argentine Republic'],
            ['code' => 'AM', 'continent_code' => 'AS', 'name' => 'Armenia', 'iso3' => 'ARM', 'number' => '051', 'full_name' => 'Republic of Armenia'],
            ['code' => 'AW', 'continent_code' => 'NA', 'name' => 'Aruba', 'iso3' => 'ABW', 'number' => '533', 'full_name' => 'Aruba'],
            ['code' => 'AU', 'continent_code' => 'OC', 'name' => 'Australia', 'iso3' => 'AUS', 'number' => '036', 'full_name' => 'Commonwealth of Australia'],
            ['code' => 'AT', 'continent_code' => 'EU', 'name' => 'Austria', 'iso3' => 'AUT', 'number' => '040', 'full_name' => 'Republic of Austria'],
            ['code' => 'AZ', 'continent_code' => 'AS', 'name' => 'Azerbaijan', 'iso3' => 'AZE', 'number' => '031', 'full_name' => 'Republic of Azerbaijan'],
            ['code' => 'BS', 'continent_code' => 'NA', 'name' => 'Bahamas', 'iso3' => 'BHS', 'number' => '044', 'full_name' => 'Commonwealth of the Bahamas'],
            ['code' => 'BH', 'continent_code' => 'AS', 'name' => 'Bahrain', 'iso3' => 'BHR', 'number' => '048', 'full_name' => 'Kingdom of Bahrain'],
            ['code' => 'BD', 'continent_code' => 'AS', 'name' => 'Bangladesh', 'iso3' => 'BGD', 'number' => '050', 'full_name' => "People's Republic of Bangladesh"],
            ['code' => 'BB', 'continent_code' => 'NA', 'name' => 'Barbados', 'iso3' => 'BRB', 'number' => '052', 'full_name' => 'Barbados'],
            ['code' => 'BY', 'continent_code' => 'EU', 'name' => 'Belarus', 'iso3' => 'BLR', 'number' => '112', 'full_name' => 'Republic of Belarus'],
            ['code' => 'BE', 'continent_code' => 'EU', 'name' => 'Belgium', 'iso3' => 'BEL', 'number' => '056', 'full_name' => 'Kingdom of Belgium'],
            ['code' => 'BZ', 'continent_code' => 'NA', 'name' => 'Belize', 'iso3' => 'BLZ', 'number' => '084', 'full_name' => 'Belize'],
            ['code' => 'BJ', 'continent_code' => 'AF', 'name' => 'Benin', 'iso3' => 'BEN', 'number' => '204', 'full_name' => 'Republic of Benin'],
            ['code' => 'BM', 'continent_code' => 'NA', 'name' => 'Bermuda', 'iso3' => 'BMU', 'number' => '060', 'full_name' => 'Bermuda'],
            ['code' => 'BT', 'continent_code' => 'AS', 'name' => 'Bhutan', 'iso3' => 'BTN', 'number' => '064', 'full_name' => 'Kingdom of Bhutan'],
            ['code' => 'BO', 'continent_code' => 'SA', 'name' => 'Bolivia', 'iso3' => 'BOL', 'number' => '068', 'full_name' => 'Plurinational State of Bolivia'],
            ['code' => 'BQ', 'continent_code' => 'NA', 'name' => 'Bonaire, Sint Eustatius and Saba', 'iso3' => 'BES', 'number' => '535', 'full_name' => 'Bonaire, Sint Eustatius and Saba'],
            ['code' => 'BA', 'continent_code' => 'EU', 'name' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'number' => '070', 'full_name' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'continent_code' => 'AF', 'name' => 'Botswana', 'iso3' => 'BWA', 'number' => '072', 'full_name' => 'Republic of Botswana'],
            ['code' => 'BV', 'continent_code' => 'AN', 'name' => 'Bouvet Island (Bouvetøya)', 'iso3' => 'BVT', 'number' => '074', 'full_name' => 'Bouvet Island (Bouvetøya)'],
            ['code' => 'BR', 'continent_code' => 'SA', 'name' => 'Brazil', 'iso3' => 'BRA', 'number' => '076', 'full_name' => 'Federative Republic of Brazil'],
            ['code' => 'IO', 'continent_code' => 'AS', 'name' => 'British Indian Ocean Territory (Chagos Archipelago)', 'iso3' => 'IOT', 'number' => '086', 'full_name' => 'British Indian Ocean Territory (Chagos Archipelago)'],
            ['code' => 'VG', 'continent_code' => 'NA', 'name' => 'British Virgin Islands', 'iso3' => 'VGB', 'number' => '092', 'full_name' => 'British Virgin Islands'],
            ['code' => 'BN', 'continent_code' => 'AS', 'name' => 'Brunei Darussalam', 'iso3' => 'BRN', 'number' => '096', 'full_name' => 'Brunei Darussalam'],
            ['code' => 'BG', 'continent_code' => 'EU', 'name' => 'Bulgaria', 'iso3' => 'BGR', 'number' => '100', 'full_name' => 'Republic of Bulgaria'],
            ['code' => 'BF', 'continent_code' => 'AF', 'name' => 'Burkina Faso', 'iso3' => 'BFA', 'number' => '854', 'full_name' => 'Burkina Faso'],
            ['code' => 'BI', 'continent_code' => 'AF', 'name' => 'Burundi', 'iso3' => 'BDI', 'number' => '108', 'full_name' => 'Republic of Burundi'],
            ['code' => 'KH', 'continent_code' => 'AS', 'name' => 'Cambodia', 'iso3' => 'KHM', 'number' => '116', 'full_name' => 'Kingdom of Cambodia'],
            ['code' => 'CM', 'continent_code' => 'AF', 'name' => 'Cameroon', 'iso3' => 'CMR', 'number' => '120', 'full_name' => 'Republic of Cameroon'],
            ['code' => 'CA', 'continent_code' => 'NA', 'name' => 'Canada', 'iso3' => 'CAN', 'number' => '124', 'full_name' => 'Canada'],
            ['code' => 'CV', 'continent_code' => 'AF', 'name' => 'Cabo Verde', 'iso3' => 'CPV', 'number' => '132', 'full_name' => 'Republic of Cabo Verde'],
            ['code' => 'KY', 'continent_code' => 'NA', 'name' => 'Cayman Islands', 'iso3' => 'CYM', 'number' => '136', 'full_name' => 'Cayman Islands'],
            ['code' => 'CF', 'continent_code' => 'AF', 'name' => 'Central African Republic', 'iso3' => 'CAF', 'number' => '140', 'full_name' => 'Central African Republic'],
            ['code' => 'TD', 'continent_code' => 'AF', 'name' => 'Chad', 'iso3' => 'TCD', 'number' => '148', 'full_name' => 'Republic of Chad'],
            ['code' => 'CL', 'continent_code' => 'SA', 'name' => 'Chile', 'iso3' => 'CHL', 'number' => '152', 'full_name' => 'Republic of Chile'],
            ['code' => 'CN', 'continent_code' => 'AS', 'name' => 'China', 'iso3' => 'CHN', 'number' => '156', 'full_name' => "People's Republic of China"],
            ['code' => 'CX', 'continent_code' => 'AS', 'name' => 'Christmas Island', 'iso3' => 'CXR', 'number' => '162', 'full_name' => 'Christmas Island'],
            ['code' => 'CC', 'continent_code' => 'AS', 'name' => 'Cocos (Keeling) Islands', 'iso3' => 'CCK', 'number' => '166', 'full_name' => 'Cocos (Keeling) Islands'],
            ['code' => 'CO', 'continent_code' => 'SA', 'name' => 'Colombia', 'iso3' => 'COL', 'number' => '170', 'full_name' => 'Republic of Colombia'],
            ['code' => 'KM', 'continent_code' => 'AF', 'name' => 'Comoros', 'iso3' => 'COM', 'number' => '174', 'full_name' => 'Union of the Comoros'],
            ['code' => 'CD', 'continent_code' => 'AF', 'name' => 'Congo', 'iso3' => 'COD', 'number' => '180', 'full_name' => 'Democratic Republic of the Congo'],
            ['code' => 'CG', 'continent_code' => 'AF', 'name' => 'Congo', 'iso3' => 'COG', 'number' => '178', 'full_name' => 'Republic of the Congo'],
            ['code' => 'CK', 'continent_code' => 'OC', 'name' => 'Cook Islands', 'iso3' => 'COK', 'number' => '184', 'full_name' => 'Cook Islands'],
            ['code' => 'CR', 'continent_code' => 'NA', 'name' => 'Costa Rica', 'iso3' => 'CRI', 'number' => '188', 'full_name' => 'Republic of Costa Rica'],
            ['code' => 'CI', 'continent_code' => 'AF', 'name' => "Cote d'Ivoire", 'iso3' => 'CIV', 'number' => '384', 'full_name' => "Republic of Cote d'Ivoire"],
            ['code' => 'HR', 'continent_code' => 'EU', 'name' => 'Croatia', 'iso3' => 'HRV', 'number' => '191', 'full_name' => 'Republic of Croatia'],
            ['code' => 'CU', 'continent_code' => 'NA', 'name' => 'Cuba', 'iso3' => 'CUB', 'number' => '192', 'full_name' => 'Republic of Cuba'],
            ['code' => 'CW', 'continent_code' => 'NA', 'name' => 'Curaçao', 'iso3' => 'CUW', 'number' => '531', 'full_name' => 'Curaçao'],
            ['code' => 'CY', 'continent_code' => 'AS', 'name' => 'Cyprus', 'iso3' => 'CYP', 'number' => '196', 'full_name' => 'Republic of Cyprus'],
            ['code' => 'CZ', 'continent_code' => 'EU', 'name' => 'Czechia', 'iso3' => 'CZE', 'number' => '203', 'full_name' => 'Czech Republic'],
            ['code' => 'DK', 'continent_code' => 'EU', 'name' => 'Denmark', 'iso3' => 'DNK', 'number' => '208', 'full_name' => 'Kingdom of Denmark'],
            ['code' => 'DJ', 'continent_code' => 'AF', 'name' => 'Djibouti', 'iso3' => 'DJI', 'number' => '262', 'full_name' => 'Republic of Djibouti'],
            ['code' => 'DM', 'continent_code' => 'NA', 'name' => 'Dominica', 'iso3' => 'DMA', 'number' => '212', 'full_name' => 'Commonwealth of Dominica'],
            ['code' => 'DO', 'continent_code' => 'NA', 'name' => 'Dominican Republic', 'iso3' => 'DOM', 'number' => '214', 'full_name' => 'Dominican Republic'],
            ['code' => 'EC', 'continent_code' => 'SA', 'name' => 'Ecuador', 'iso3' => 'ECU', 'number' => '218', 'full_name' => 'Republic of Ecuador'],
            ['code' => 'EG', 'continent_code' => 'AF', 'name' => 'Egypt', 'iso3' => 'EGY', 'number' => '818', 'full_name' => 'Arab Republic of Egypt'],
            ['code' => 'SV', 'continent_code' => 'NA', 'name' => 'El Salvador', 'iso3' => 'SLV', 'number' => '222', 'full_name' => 'Republic of El Salvador'],
            ['code' => 'GQ', 'continent_code' => 'AF', 'name' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'number' => '226', 'full_name' => 'Republic of Equatorial Guinea'],
            ['code' => 'ER', 'continent_code' => 'AF', 'name' => 'Eritrea', 'iso3' => 'ERI', 'number' => '232', 'full_name' => 'State of Eritrea'],
            ['code' => 'EE', 'continent_code' => 'EU', 'name' => 'Estonia', 'iso3' => 'EST', 'number' => '233', 'full_name' => 'Republic of Estonia'],
            ['code' => 'ET', 'continent_code' => 'AF', 'name' => 'Ethiopia', 'iso3' => 'ETH', 'number' => '231', 'full_name' => 'Federal Democratic Republic of Ethiopia'],
            ['code' => 'FO', 'continent_code' => 'EU', 'name' => 'Faroe Islands', 'iso3' => 'FRO', 'number' => '234', 'full_name' => 'Faroe Islands'],
            ['code' => 'FK', 'continent_code' => 'SA', 'name' => 'Falkland Islands (Malvinas)', 'iso3' => 'FLK', 'number' => '238', 'full_name' => 'Falkland Islands (Malvinas)'],
            ['code' => 'FJ', 'continent_code' => 'OC', 'name' => 'Fiji', 'iso3' => 'FJI', 'number' => '242', 'full_name' => 'Republic of Fiji'],
            ['code' => 'FI', 'continent_code' => 'EU', 'name' => 'Finland', 'iso3' => 'FIN', 'number' => '246', 'full_name' => 'Republic of Finland'],
            ['code' => 'FR', 'continent_code' => 'EU', 'name' => 'France', 'iso3' => 'FRA', 'number' => '250', 'full_name' => 'French Republic'],
            ['code' => 'GF', 'continent_code' => 'SA', 'name' => 'French Guiana', 'iso3' => 'GUF', 'number' => '254', 'full_name' => 'French Guiana'],
            ['code' => 'PF', 'continent_code' => 'OC', 'name' => 'French Polynesia', 'iso3' => 'PYF', 'number' => '258', 'full_name' => 'French Polynesia'],
            ['code' => 'TF', 'continent_code' => 'AN', 'name' => 'French Southern Territories', 'iso3' => 'ATF', 'number' => '260', 'full_name' => 'French Southern Territories'],
            ['code' => 'GA', 'continent_code' => 'AF', 'name' => 'Gabon', 'iso3' => 'GAB', 'number' => '266', 'full_name' => 'Gabonese Republic'],
            ['code' => 'GM', 'continent_code' => 'AF', 'name' => 'Gambia', 'iso3' => 'GMB', 'number' => '270', 'full_name' => 'Republic of the Gambia'],
            ['code' => 'GE', 'continent_code' => 'AS', 'name' => 'Georgia', 'iso3' => 'GEO', 'number' => '268', 'full_name' => 'Georgia'],
            ['code' => 'DE', 'continent_code' => 'EU', 'name' => 'Germany', 'iso3' => 'DEU', 'number' => '276', 'full_name' => 'Federal Republic of Germany'],
            ['code' => 'GH', 'continent_code' => 'AF', 'name' => 'Ghana', 'iso3' => 'GHA', 'number' => '288', 'full_name' => 'Republic of Ghana'],
            ['code' => 'GI', 'continent_code' => 'EU', 'name' => 'Gibraltar', 'iso3' => 'GIB', 'number' => '292', 'full_name' => 'Gibraltar'],
            ['code' => 'GR', 'continent_code' => 'EU', 'name' => 'Greece', 'iso3' => 'GRC', 'number' => '300', 'full_name' => 'Hellenic Republic of Greece'],
            ['code' => 'GL', 'continent_code' => 'NA', 'name' => 'Greenland', 'iso3' => 'GRL', 'number' => '304', 'full_name' => 'Greenland'],
            ['code' => 'GD', 'continent_code' => 'NA', 'name' => 'Grenada', 'iso3' => 'GRD', 'number' => '308', 'full_name' => 'Grenada'],
            ['code' => 'GP', 'continent_code' => 'NA', 'name' => 'Guadeloupe', 'iso3' => 'GLP', 'number' => '312', 'full_name' => 'Guadeloupe'],
            ['code' => 'GU', 'continent_code' => 'OC', 'name' => 'Guam', 'iso3' => 'GUM', 'number' => '316', 'full_name' => 'Guam'],
            ['code' => 'GT', 'continent_code' => 'NA', 'name' => 'Guatemala', 'iso3' => 'GTM', 'number' => '320', 'full_name' => 'Republic of Guatemala'],
            ['code' => 'GG', 'continent_code' => 'EU', 'name' => 'Guernsey', 'iso3' => 'GGY', 'number' => '831', 'full_name' => 'Bailiwick of Guernsey'],
            ['code' => 'GN', 'continent_code' => 'AF', 'name' => 'Guinea', 'iso3' => 'GIN', 'number' => '324', 'full_name' => 'Republic of Guinea'],
            ['code' => 'GW', 'continent_code' => 'AF', 'name' => 'Guinea-Bissau', 'iso3' => 'GNB', 'number' => '624', 'full_name' => 'Republic of Guinea-Bissau'],
            ['code' => 'GY', 'continent_code' => 'SA', 'name' => 'Guyana', 'iso3' => 'GUY', 'number' => '328', 'full_name' => 'Co-operative Republic of Guyana'],
            ['code' => 'HT', 'continent_code' => 'NA', 'name' => 'Haiti', 'iso3' => 'HTI', 'number' => '332', 'full_name' => 'Republic of Haiti'],
            ['code' => 'HM', 'continent_code' => 'AN', 'name' => 'Heard Island and McDonald Islands', 'iso3' => 'HMD', 'number' => '334', 'full_name' => 'Heard Island and McDonald Islands'],
            ['code' => 'VA', 'continent_code' => 'EU', 'name' => 'Holy See (Vatican City State)', 'iso3' => 'VAT', 'number' => '336', 'full_name' => 'Holy See (Vatican City State)'],
            ['code' => 'HN', 'continent_code' => 'NA', 'name' => 'Honduras', 'iso3' => 'HND', 'number' => '340', 'full_name' => 'Republic of Honduras'],
            ['code' => 'HK', 'continent_code' => 'AS', 'name' => 'Hong Kong', 'iso3' => 'HKG', 'number' => '344', 'full_name' => 'Hong Kong Special Administrative Region of China'],
            ['code' => 'HU', 'continent_code' => 'EU', 'name' => 'Hungary', 'iso3' => 'HUN', 'number' => '348', 'full_name' => 'Hungary'],
            ['code' => 'IS', 'continent_code' => 'EU', 'name' => 'Iceland', 'iso3' => 'ISL', 'number' => '352', 'full_name' => 'Iceland'],
            ['code' => 'IN', 'continent_code' => 'AS', 'name' => 'India', 'iso3' => 'IND', 'number' => '356', 'full_name' => 'Republic of India'],
            ['code' => 'ID', 'continent_code' => 'AS', 'name' => 'Indonesia', 'iso3' => 'IDN', 'number' => '360', 'full_name' => 'Republic of Indonesia'],
            ['code' => 'IR', 'continent_code' => 'AS', 'name' => 'Iran', 'iso3' => 'IRN', 'number' => '364', 'full_name' => 'Islamic Republic of Iran'],
            ['code' => 'IQ', 'continent_code' => 'AS', 'name' => 'Iraq', 'iso3' => 'IRQ', 'number' => '368', 'full_name' => 'Republic of Iraq'],
            ['code' => 'IE', 'continent_code' => 'EU', 'name' => 'Ireland', 'iso3' => 'IRL', 'number' => '372', 'full_name' => 'Ireland'],
            ['code' => 'IM', 'continent_code' => 'EU', 'name' => 'Isle of Man', 'iso3' => 'IMN', 'number' => '833', 'full_name' => 'Isle of Man'],
            ['code' => 'IL', 'continent_code' => 'AS', 'name' => 'Israel', 'iso3' => 'ISR', 'number' => '376', 'full_name' => 'State of Israel'],
            ['code' => 'IT', 'continent_code' => 'EU', 'name' => 'Italy', 'iso3' => 'ITA', 'number' => '380', 'full_name' => 'Republic of Italy'],
            ['code' => 'JM', 'continent_code' => 'NA', 'name' => 'Jamaica', 'iso3' => 'JAM', 'number' => '388', 'full_name' => 'Jamaica'],
            ['code' => 'JP', 'continent_code' => 'AS', 'name' => 'Japan', 'iso3' => 'JPN', 'number' => '392', 'full_name' => 'Japan'],
            ['code' => 'JE', 'continent_code' => 'EU', 'name' => 'Jersey', 'iso3' => 'JEY', 'number' => '832', 'full_name' => 'Bailiwick of Jersey'],
            ['code' => 'JO', 'continent_code' => 'AS', 'name' => 'Jordan', 'iso3' => 'JOR', 'number' => '400', 'full_name' => 'Hashemite Kingdom of Jordan'],
            ['code' => 'KZ', 'continent_code' => 'AS', 'name' => 'Kazakhstan', 'iso3' => 'KAZ', 'number' => '398', 'full_name' => 'Republic of Kazakhstan'],
            ['code' => 'KE', 'continent_code' => 'AF', 'name' => 'Kenya', 'iso3' => 'KEN', 'number' => '404', 'full_name' => 'Republic of Kenya'],
            ['code' => 'KI', 'continent_code' => 'OC', 'name' => 'Kiribati', 'iso3' => 'KIR', 'number' => '296', 'full_name' => 'Republic of Kiribati'],
            ['code' => 'KP', 'continent_code' => 'AS', 'name' => 'Korea', 'iso3' => 'PRK', 'number' => '408', 'full_name' => "Democratic People's Republic of Korea"],
            ['code' => 'KR', 'continent_code' => 'AS', 'name' => 'Korea', 'iso3' => 'KOR', 'number' => '410', 'full_name' => 'Republic of Korea'],
            ['code' => 'KW', 'continent_code' => 'AS', 'name' => 'Kuwait', 'iso3' => 'KWT', 'number' => '414', 'full_name' => 'State of Kuwait'],
            ['code' => 'KG', 'continent_code' => 'AS', 'name' => 'Kyrgyz Republic', 'iso3' => 'KGZ', 'number' => '417', 'full_name' => 'Kyrgyz Republic'],
            ['code' => 'LA', 'continent_code' => 'AS', 'name' => "Lao People's Democratic Republic", 'iso3' => 'LAO', 'number' => '418', 'full_name' => "Lao People's Democratic Republic"],
            ['code' => 'LV', 'continent_code' => 'EU', 'name' => 'Latvia', 'iso3' => 'LVA', 'number' => '428', 'full_name' => 'Republic of Latvia'],
            ['code' => 'LB', 'continent_code' => 'AS', 'name' => 'Lebanon', 'iso3' => 'LBN', 'number' => '422', 'full_name' => 'Lebanese Republic'],
            ['code' => 'LS', 'continent_code' => 'AF', 'name' => 'Lesotho', 'iso3' => 'LSO', 'number' => '426', 'full_name' => 'Kingdom of Lesotho'],
            ['code' => 'LR', 'continent_code' => 'AF', 'name' => 'Liberia', 'iso3' => 'LBR', 'number' => '430', 'full_name' => 'Republic of Liberia'],
            ['code' => 'LY', 'continent_code' => 'AF', 'name' => 'Libya', 'iso3' => 'LBY', 'number' => '434', 'full_name' => 'State of Libya'],
            ['code' => 'LI', 'continent_code' => 'EU', 'name' => 'Liechtenstein', 'iso3' => 'LIE', 'number' => '438', 'full_name' => 'Principality of Liechtenstein'],
            ['code' => 'LT', 'continent_code' => 'EU', 'name' => 'Lithuania', 'iso3' => 'LTU', 'number' => '440', 'full_name' => 'Republic of Lithuania'],
            ['code' => 'LU', 'continent_code' => 'EU', 'name' => 'Luxembourg', 'iso3' => 'LUX', 'number' => '442', 'full_name' => 'Grand Duchy of Luxembourg'],
            ['code' => 'MO', 'continent_code' => 'AS', 'name' => 'Macao', 'iso3' => 'MAC', 'number' => '446', 'full_name' => 'Macao Special Administrative Region of China'],
            ['code' => 'MG', 'continent_code' => 'AF', 'name' => 'Madagascar', 'iso3' => 'MDG', 'number' => '450', 'full_name' => 'Republic of Madagascar'],
            ['code' => 'MW', 'continent_code' => 'AF', 'name' => 'Malawi', 'iso3' => 'MWI', 'number' => '454', 'full_name' => 'Republic of Malawi'],
            ['code' => 'MY', 'continent_code' => 'AS', 'name' => 'Malaysia', 'iso3' => 'MYS', 'number' => '458', 'full_name' => 'Malaysia'],
            ['code' => 'MV', 'continent_code' => 'AS', 'name' => 'Maldives', 'iso3' => 'MDV', 'number' => '462', 'full_name' => 'Republic of Maldives'],
            ['code' => 'ML', 'continent_code' => 'AF', 'name' => 'Mali', 'iso3' => 'MLI', 'number' => '466', 'full_name' => 'Republic of Mali'],
            ['code' => 'MT', 'continent_code' => 'EU', 'name' => 'Malta', 'iso3' => 'MLT', 'number' => '470', 'full_name' => 'Republic of Malta'],
            ['code' => 'MH', 'continent_code' => 'OC', 'name' => 'Marshall Islands', 'iso3' => 'MHL', 'number' => '584', 'full_name' => 'Republic of the Marshall Islands'],
            ['code' => 'MQ', 'continent_code' => 'NA', 'name' => 'Martinique', 'iso3' => 'MTQ', 'number' => '474', 'full_name' => 'Martinique'],
            ['code' => 'MR', 'continent_code' => 'AF', 'name' => 'Mauritania', 'iso3' => 'MRT', 'number' => '478', 'full_name' => 'Islamic Republic of Mauritania'],
            ['code' => 'MU', 'continent_code' => 'AF', 'name' => 'Mauritius', 'iso3' => 'MUS', 'number' => '480', 'full_name' => 'Republic of Mauritius'],
            ['code' => 'YT', 'continent_code' => 'AF', 'name' => 'Mayotte', 'iso3' => 'MYT', 'number' => '175', 'full_name' => 'Mayotte'],
            ['code' => 'MX', 'continent_code' => 'NA', 'name' => 'Mexico', 'iso3' => 'MEX', 'number' => '484', 'full_name' => 'United Mexican States'],
            ['code' => 'FM', 'continent_code' => 'OC', 'name' => 'Micronesia', 'iso3' => 'FSM', 'number' => '583', 'full_name' => 'Federated States of Micronesia'],
            ['code' => 'MD', 'continent_code' => 'EU', 'name' => 'Moldova', 'iso3' => 'MDA', 'number' => '498', 'full_name' => 'Republic of Moldova'],
            ['code' => 'MC', 'continent_code' => 'EU', 'name' => 'Monaco', 'iso3' => 'MCO', 'number' => '492', 'full_name' => 'Principality of Monaco'],
            ['code' => 'MN', 'continent_code' => 'AS', 'name' => 'Mongolia', 'iso3' => 'MNG', 'number' => '496', 'full_name' => 'Mongolia'],
            ['code' => 'ME', 'continent_code' => 'EU', 'name' => 'Montenegro', 'iso3' => 'MNE', 'number' => '499', 'full_name' => 'Montenegro'],
            ['code' => 'MS', 'continent_code' => 'NA', 'name' => 'Montserrat', 'iso3' => 'MSR', 'number' => '500', 'full_name' => 'Montserrat'],
            ['code' => 'MA', 'continent_code' => 'AF', 'name' => 'Morocco', 'iso3' => 'MAR', 'number' => '504', 'full_name' => 'Kingdom of Morocco'],
            ['code' => 'MZ', 'continent_code' => 'AF', 'name' => 'Mozambique', 'iso3' => 'MOZ', 'number' => '508', 'full_name' => 'Republic of Mozambique'],
            ['code' => 'MM', 'continent_code' => 'AS', 'name' => 'Myanmar', 'iso3' => 'MMR', 'number' => '104', 'full_name' => 'Republic of the Union of Myanmar'],
            ['code' => 'NA', 'continent_code' => 'AF', 'name' => 'Namibia', 'iso3' => 'NAM', 'number' => '516', 'full_name' => 'Republic of Namibia'],
            ['code' => 'NR', 'continent_code' => 'OC', 'name' => 'Nauru', 'iso3' => 'NRU', 'number' => '520', 'full_name' => 'Republic of Nauru'],
            ['code' => 'NP', 'continent_code' => 'AS', 'name' => 'Nepal', 'iso3' => 'NPL', 'number' => '524', 'full_name' => 'Nepal'],
            ['code' => 'NL', 'continent_code' => 'EU', 'name' => 'Netherlands', 'iso3' => 'NLD', 'number' => '528', 'full_name' => 'Kingdom of the Netherlands'],
            ['code' => 'NC', 'continent_code' => 'OC', 'name' => 'New Caledonia', 'iso3' => 'NCL', 'number' => '540', 'full_name' => 'New Caledonia'],
            ['code' => 'NZ', 'continent_code' => 'OC', 'name' => 'New Zealand', 'iso3' => 'NZL', 'number' => '554', 'full_name' => 'New Zealand'],
            ['code' => 'NI', 'continent_code' => 'NA', 'name' => 'Nicaragua', 'iso3' => 'NIC', 'number' => '558', 'full_name' => 'Republic of Nicaragua'],
            ['code' => 'NE', 'continent_code' => 'AF', 'name' => 'Niger', 'iso3' => 'NER', 'number' => '562', 'full_name' => 'Republic of Niger'],
            ['code' => 'NG', 'continent_code' => 'AF', 'name' => 'Nigeria', 'iso3' => 'NGA', 'number' => '566', 'full_name' => 'Federal Republic of Nigeria'],
            ['code' => 'NU', 'continent_code' => 'OC', 'name' => 'Niue', 'iso3' => 'NIU', 'number' => '570', 'full_name' => 'Niue'],
            ['code' => 'NF', 'continent_code' => 'OC', 'name' => 'Norfolk Island', 'iso3' => 'NFK', 'number' => '574', 'full_name' => 'Norfolk Island'],
            ['code' => 'MK', 'continent_code' => 'EU', 'name' => 'North Macedonia', 'iso3' => 'MKD', 'number' => '807', 'full_name' => 'Republic of North Macedonia'],
            ['code' => 'MP', 'continent_code' => 'OC', 'name' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'number' => '580', 'full_name' => 'Commonwealth of the Northern Mariana Islands'],
            ['code' => 'NO', 'continent_code' => 'EU', 'name' => 'Norway', 'iso3' => 'NOR', 'number' => '578', 'full_name' => 'Kingdom of Norway'],
            ['code' => 'OM', 'continent_code' => 'AS', 'name' => 'Oman', 'iso3' => 'OMN', 'number' => '512', 'full_name' => 'Sultanate of Oman'],
            ['code' => 'PK', 'continent_code' => 'AS', 'name' => 'Pakistan', 'iso3' => 'PAK', 'number' => '586', 'full_name' => 'Islamic Republic of Pakistan'],
            ['code' => 'PW', 'continent_code' => 'OC', 'name' => 'Palau', 'iso3' => 'PLW', 'number' => '585', 'full_name' => 'Republic of Palau'],
            ['code' => 'PS', 'continent_code' => 'AS', 'name' => 'Palestine', 'iso3' => 'PSE', 'number' => '275', 'full_name' => 'State of Palestine'],
            ['code' => 'PA', 'continent_code' => 'NA', 'name' => 'Panama', 'iso3' => 'PAN', 'number' => '591', 'full_name' => 'Republic of Panama'],
            ['code' => 'PG', 'continent_code' => 'OC', 'name' => 'Papua New Guinea', 'iso3' => 'PNG', 'number' => '598', 'full_name' => 'Independent State of Papua New Guinea'],
            ['code' => 'PY', 'continent_code' => 'SA', 'name' => 'Paraguay', 'iso3' => 'PRY', 'number' => '600', 'full_name' => 'Republic of Paraguay'],
            ['code' => 'PE', 'continent_code' => 'SA', 'name' => 'Peru', 'iso3' => 'PER', 'number' => '604', 'full_name' => 'Republic of Peru'],
            ['code' => 'PH', 'continent_code' => 'AS', 'name' => 'Philippines', 'iso3' => 'PHL', 'number' => '608', 'full_name' => 'Republic of the Philippines'],
            ['code' => 'PN', 'continent_code' => 'OC', 'name' => 'Pitcairn Islands', 'iso3' => 'PCN', 'number' => '612', 'full_name' => 'Pitcairn Islands'],
            ['code' => 'PL', 'continent_code' => 'EU', 'name' => 'Poland', 'iso3' => 'POL', 'number' => '616', 'full_name' => 'Republic of Poland'],
            ['code' => 'PT', 'continent_code' => 'EU', 'name' => 'Portugal', 'iso3' => 'PRT', 'number' => '620', 'full_name' => 'Portuguese Republic'],
            ['code' => 'PR', 'continent_code' => 'NA', 'name' => 'Puerto Rico', 'iso3' => 'PRI', 'number' => '630', 'full_name' => 'Commonwealth of Puerto Rico'],
            ['code' => 'QA', 'continent_code' => 'AS', 'name' => 'Qatar', 'iso3' => 'QAT', 'number' => '634', 'full_name' => 'State of Qatar'],
            ['code' => 'RE', 'continent_code' => 'AF', 'name' => 'Réunion', 'iso3' => 'REU', 'number' => '638', 'full_name' => 'Réunion'],
            ['code' => 'RO', 'continent_code' => 'EU', 'name' => 'Romania', 'iso3' => 'ROU', 'number' => '642', 'full_name' => 'Romania'],
            ['code' => 'RU', 'continent_code' => 'EU', 'name' => 'Russian Federation', 'iso3' => 'RUS', 'number' => '643', 'full_name' => 'Russian Federation'],
            ['code' => 'RW', 'continent_code' => 'AF', 'name' => 'Rwanda', 'iso3' => 'RWA', 'number' => '646', 'full_name' => 'Republic of Rwanda'],
            ['code' => 'BL', 'continent_code' => 'NA', 'name' => 'Saint Barthélemy', 'iso3' => 'BLM', 'number' => '652', 'full_name' => 'Saint Barthélemy'],
            ['code' => 'SH', 'continent_code' => 'AF', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso3' => 'SHN', 'number' => '654', 'full_name' => 'Saint Helena, Ascension and Tristan da Cunha'],
            ['code' => 'KN', 'continent_code' => 'NA', 'name' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'number' => '659', 'full_name' => 'Federation of Saint Kitts and Nevis'],
            ['code' => 'LC', 'continent_code' => 'NA', 'name' => 'Saint Lucia', 'iso3' => 'LCA', 'number' => '662', 'full_name' => 'Saint Lucia'],
            ['code' => 'MF', 'continent_code' => 'NA', 'name' => 'Saint Martin', 'iso3' => 'MAF', 'number' => '663', 'full_name' => 'Saint Martin (French part)'],
            ['code' => 'PM', 'continent_code' => 'NA', 'name' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'number' => '666', 'full_name' => 'Saint Pierre and Miquelon'],
            ['code' => 'VC', 'continent_code' => 'NA', 'name' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'number' => '670', 'full_name' => 'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'continent_code' => 'OC', 'name' => 'Samoa', 'iso3' => 'WSM', 'number' => '882', 'full_name' => 'Independent State of Samoa'],
            ['code' => 'SM', 'continent_code' => 'EU', 'name' => 'San Marino', 'iso3' => 'SMR', 'number' => '674', 'full_name' => 'Republic of San Marino'],
            ['code' => 'ST', 'continent_code' => 'AF', 'name' => 'Sao Tome and Principe', 'iso3' => 'STP', 'number' => '678', 'full_name' => 'Democratic Republic of Sao Tome and Principe'],
            ['code' => 'SA', 'continent_code' => 'AS', 'name' => 'Saudi Arabia', 'iso3' => 'SAU', 'number' => '682', 'full_name' => 'Kingdom of Saudi Arabia'],
            ['code' => 'SN', 'continent_code' => 'AF', 'name' => 'Senegal', 'iso3' => 'SEN', 'number' => '686', 'full_name' => 'Republic of Senegal'],
            ['code' => 'RS', 'continent_code' => 'EU', 'name' => 'Serbia', 'iso3' => 'SRB', 'number' => '688', 'full_name' => 'Republic of Serbia'],
            ['code' => 'SC', 'continent_code' => 'AF', 'name' => 'Seychelles', 'iso3' => 'SYC', 'number' => '690', 'full_name' => 'Republic of Seychelles'],
            ['code' => 'SL', 'continent_code' => 'AF', 'name' => 'Sierra Leone', 'iso3' => 'SLE', 'number' => '694', 'full_name' => 'Republic of Sierra Leone'],
            ['code' => 'SG', 'continent_code' => 'AS', 'name' => 'Singapore', 'iso3' => 'SGP', 'number' => '702', 'full_name' => 'Republic of Singapore'],
            ['code' => 'SX', 'continent_code' => 'NA', 'name' => 'Sint Maarten (Dutch part)', 'iso3' => 'SXM', 'number' => '534', 'full_name' => 'Sint Maarten (Dutch part)'],
            ['code' => 'SK', 'continent_code' => 'EU', 'name' => 'Slovakia (Slovak Republic)', 'iso3' => 'SVK', 'number' => '703', 'full_name' => 'Slovakia (Slovak Republic)'],
            ['code' => 'SI', 'continent_code' => 'EU', 'name' => 'Slovenia', 'iso3' => 'SVN', 'number' => '705', 'full_name' => 'Republic of Slovenia'],
            ['code' => 'SB', 'continent_code' => 'OC', 'name' => 'Solomon Islands', 'iso3' => 'SLB', 'number' => '090', 'full_name' => 'Solomon Islands'],
            ['code' => 'SO', 'continent_code' => 'AF', 'name' => 'Somalia', 'iso3' => 'SOM', 'number' => '706', 'full_name' => 'Federal Republic of Somalia'],
            ['code' => 'ZA', 'continent_code' => 'AF', 'name' => 'South Africa', 'iso3' => 'ZAF', 'number' => '710', 'full_name' => 'Republic of South Africa'],
            ['code' => 'GS', 'continent_code' => 'AN', 'name' => 'South Georgia and the South Sandwich Islands', 'iso3' => 'SGS', 'number' => '239', 'full_name' => 'South Georgia and the South Sandwich Islands'],
            ['code' => 'SS', 'continent_code' => 'AF', 'name' => 'South Sudan', 'iso3' => 'SSD', 'number' => '728', 'full_name' => 'Republic of South Sudan'],
            ['code' => 'ES', 'continent_code' => 'EU', 'name' => 'Spain', 'iso3' => 'ESP', 'number' => '724', 'full_name' => 'Kingdom of Spain'],
            ['code' => 'LK', 'continent_code' => 'AS', 'name' => 'Sri Lanka', 'iso3' => 'LKA', 'number' => '144', 'full_name' => 'Democratic Socialist Republic of Sri Lanka'],
            ['code' => 'SD', 'continent_code' => 'AF', 'name' => 'Sudan', 'iso3' => 'SDN', 'number' => '729', 'full_name' => 'Republic of Sudan'],
            ['code' => 'SR', 'continent_code' => 'SA', 'name' => 'Suriname', 'iso3' => 'SUR', 'number' => '740', 'full_name' => 'Republic of Suriname'],
            ['code' => 'SJ', 'continent_code' => 'EU', 'name' => 'Svalbard & Jan Mayen Islands', 'iso3' => 'SJM', 'number' => '744', 'full_name' => 'Svalbard & Jan Mayen Islands'],
            ['code' => 'SZ', 'continent_code' => 'AF', 'name' => 'Eswatini', 'iso3' => 'SWZ', 'number' => '748', 'full_name' => 'Kingdom of Eswatini'],
            ['code' => 'SE', 'continent_code' => 'EU', 'name' => 'Sweden', 'iso3' => 'SWE', 'number' => '752', 'full_name' => 'Kingdom of Sweden'],
            ['code' => 'CH', 'continent_code' => 'EU', 'name' => 'Switzerland', 'iso3' => 'CHE', 'number' => '756', 'full_name' => 'Swiss Confederation'],
            ['code' => 'SY', 'continent_code' => 'AS', 'name' => 'Syrian Arab Republic', 'iso3' => 'SYR', 'number' => '760', 'full_name' => 'Syrian Arab Republic'],
            ['code' => 'TW', 'continent_code' => 'AS', 'name' => 'Taiwan', 'iso3' => 'TWN', 'number' => '158', 'full_name' => 'Taiwan, Province of China'],
            ['code' => 'TJ', 'continent_code' => 'AS', 'name' => 'Tajikistan', 'iso3' => 'TJK', 'number' => '762', 'full_name' => 'Republic of Tajikistan'],
            ['code' => 'TZ', 'continent_code' => 'AF', 'name' => 'Tanzania', 'iso3' => 'TZA', 'number' => '834', 'full_name' => 'United Republic of Tanzania'],
            ['code' => 'TH', 'continent_code' => 'AS', 'name' => 'Thailand', 'iso3' => 'THA', 'number' => '764', 'full_name' => 'Kingdom of Thailand'],
            ['code' => 'TL', 'continent_code' => 'AS', 'name' => 'Timor-Leste', 'iso3' => 'TLS', 'number' => '626', 'full_name' => 'Democratic Republic of Timor-Leste'],
            ['code' => 'TG', 'continent_code' => 'AF', 'name' => 'Togo', 'iso3' => 'TGO', 'number' => '768', 'full_name' => 'Togolese Republic'],
            ['code' => 'TK', 'continent_code' => 'OC', 'name' => 'Tokelau', 'iso3' => 'TKL', 'number' => '772', 'full_name' => 'Tokelau'],
            ['code' => 'TO', 'continent_code' => 'OC', 'name' => 'Tonga', 'iso3' => 'TON', 'number' => '776', 'full_name' => 'Kingdom of Tonga'],
            ['code' => 'TT', 'continent_code' => 'NA', 'name' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'number' => '780', 'full_name' => 'Republic of Trinidad and Tobago'],
            ['code' => 'TN', 'continent_code' => 'AF', 'name' => 'Tunisia', 'iso3' => 'TUN', 'number' => '788', 'full_name' => 'Tunisian Republic'],
            ['code' => 'TR', 'continent_code' => 'AS', 'name' => 'Türkiye', 'iso3' => 'TUR', 'number' => '792', 'full_name' => 'Republic of Türkiye'],
            ['code' => 'TM', 'continent_code' => 'AS', 'name' => 'Turkmenistan', 'iso3' => 'TKM', 'number' => '795', 'full_name' => 'Turkmenistan'],
            ['code' => 'TC', 'continent_code' => 'NA', 'name' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'number' => '796', 'full_name' => 'Turks and Caicos Islands'],
            ['code' => 'TV', 'continent_code' => 'OC', 'name' => 'Tuvalu', 'iso3' => 'TUV', 'number' => '798', 'full_name' => 'Tuvalu'],
            ['code' => 'UG', 'continent_code' => 'AF', 'name' => 'Uganda', 'iso3' => 'UGA', 'number' => '800', 'full_name' => 'Republic of Uganda'],
            ['code' => 'UA', 'continent_code' => 'EU', 'name' => 'Ukraine', 'iso3' => 'UKR', 'number' => '804', 'full_name' => 'Ukraine'],
            ['code' => 'AE', 'continent_code' => 'AS', 'name' => 'United Arab Emirates', 'iso3' => 'ARE', 'number' => '784', 'full_name' => 'United Arab Emirates'],
            ['code' => 'GB', 'continent_code' => 'EU', 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'iso3' => 'GBR', 'number' => '826', 'full_name' => 'United Kingdom of Great Britain & Northern Ireland'],
            ['code' => 'US', 'continent_code' => 'NA', 'name' => 'United States of America', 'iso3' => 'USA', 'number' => '840', 'full_name' => 'United States of America'],
            ['code' => 'UM', 'continent_code' => 'OC', 'name' => 'United States Minor Outlying Islands', 'iso3' => 'UMI', 'number' => '581', 'full_name' => 'United States Minor Outlying Islands'],
            ['code' => 'VI', 'continent_code' => 'NA', 'name' => 'United States Virgin Islands', 'iso3' => 'VIR', 'number' => '850', 'full_name' => 'United States Virgin Islands'],
            ['code' => 'UY', 'continent_code' => 'SA', 'name' => 'Uruguay', 'iso3' => 'URY', 'number' => '858', 'full_name' => 'Eastern Republic of Uruguay'],
            ['code' => 'UZ', 'continent_code' => 'AS', 'name' => 'Uzbekistan', 'iso3' => 'UZB', 'number' => '860', 'full_name' => 'Republic of Uzbekistan'],
            ['code' => 'VU', 'continent_code' => 'OC', 'name' => 'Vanuatu', 'iso3' => 'VUT', 'number' => '548', 'full_name' => 'Republic of Vanuatu'],
            ['code' => 'VE', 'continent_code' => 'SA', 'name' => 'Venezuela', 'iso3' => 'VEN', 'number' => '862', 'full_name' => 'Bolivarian Republic of Venezuela'],
            ['code' => 'VN', 'continent_code' => 'AS', 'name' => 'Vietnam', 'iso3' => 'VNM', 'number' => '704', 'full_name' => 'Socialist Republic of Vietnam'],
            ['code' => 'WF', 'continent_code' => 'OC', 'name' => 'Wallis and Futuna', 'iso3' => 'WLF', 'number' => '876', 'full_name' => 'Wallis and Futuna'],
            ['code' => 'EH', 'continent_code' => 'AF', 'name' => 'Western Sahara', 'iso3' => 'ESH', 'number' => '732', 'full_name' => 'Western Sahara'],
            ['code' => 'YE', 'continent_code' => 'AS', 'name' => 'Yemen', 'iso3' => 'YEM', 'number' => '887', 'full_name' => 'Yemen'],
            ['code' => 'ZM', 'continent_code' => 'AF', 'name' => 'Zambia', 'iso3' => 'ZMB', 'number' => '894', 'full_name' => 'Republic of Zambia'],
            ['code' => 'ZW', 'continent_code' => 'AF', 'name' => 'Zimbabwe', 'iso3' => 'ZWE', 'number' => '716', 'full_name' => 'Republic of Zimbabwe'],
        ]);
    }
};
